#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
RMHealth Expediente Clinico — PDF Generator
Server-side PDF generation using ReportLab.
Bilingual support (es/en) based on user language preference.
NOM-004 compliant medical record export.

© 2025 MORALES ZEPEDA RAUL | Registro INDAUTOR: 03-2025-070109072500-01
"""

import datetime
import io
from typing import Any, Dict, List, Optional

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch, mm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    PageBreak, HRFlowable,
)

# ── Bilingual translations ──────────────────────────────────────
TRANSLATIONS = {
    "es": {
        "title": "Expediente Clinico Digital",
        "subtitle": "Sistema de Monitoreo Medico RMHealth",
        "generated": "Generado",
        "version": "Version",
        "page": "Pagina",
        "patient_profile": "Perfil del Paciente",
        "name": "Nombre",
        "email": "Correo",
        "age": "Edad",
        "years": "anios",
        "blood_type": "Tipo de Sangre",
        "weight": "Peso",
        "height": "Estatura",
        "treating_doctor": "Medico Tratante",
        "medical_conditions": "Condiciones Medicas",
        "condition": "Condicion",
        "status": "Estado",
        "diagnosis_date": "Observaciones",
        "allergies": "Alergias",
        "agent": "Agente",
        "severity": "Severidad",
        "type": "Tipo",
        "emergency_contacts": "Contactos de Emergencia",
        "contact_name": "Nombre",
        "relationship": "Parentesco",
        "phone": "Telefono",
        "measurement_history": "Historial de Mediciones",
        "date": "Fecha",
        "heart_rate": "FC",
        "spo2": "SpO2",
        "systolic": "Sist",
        "diastolic": "Diast",
        "glucose": "Glu",
        "temperature": "Temp",
        "context": "Contexto",
        "total_measurements": "Total de mediciones",
        "monitoring_period": "Periodo de monitoreo",
        "to": "a",
        "medications_adherence": "Medicamentos y Adherencia",
        "medication": "Medicamento",
        "dose": "Dosis",
        "schedule": "Horario",
        "days": "Dias",
        "active": "Activo",
        "inactive": "Inactivo",
        "resolved": "Resuelto",
        "adherence": "Adherencia",
        "yes": "Si",
        "no": "No",
        "no_data": "Sin datos registrados",
        "legal_notice": (
            "Este documento es un resumen del expediente clinico digital generado por el sistema RMHealth. "
            "Los datos contenidos son de caracter informativo y no sustituyen el criterio medico profesional. "
            "Conservacion minima de 5 anios conforme a la NOM-004-SSA3-2012."
        ),
        "confidential": "CONFIDENCIAL — Informacion medica protegida",
        "special_instructions": "Instrucciones Especiales",
    },
    "en": {
        "title": "Digital Clinical Record",
        "subtitle": "RMHealth Medical Monitoring System",
        "generated": "Generated",
        "version": "Version",
        "page": "Page",
        "patient_profile": "Patient Profile",
        "name": "Name",
        "email": "Email",
        "age": "Age",
        "years": "years",
        "blood_type": "Blood Type",
        "weight": "Weight",
        "height": "Height",
        "treating_doctor": "Treating Doctor",
        "medical_conditions": "Medical Conditions",
        "condition": "Condition",
        "status": "Status",
        "diagnosis_date": "Observations",
        "allergies": "Allergies",
        "agent": "Agent",
        "severity": "Severity",
        "type": "Type",
        "emergency_contacts": "Emergency Contacts",
        "contact_name": "Name",
        "relationship": "Relationship",
        "phone": "Phone",
        "measurement_history": "Measurement History",
        "date": "Date",
        "heart_rate": "HR",
        "spo2": "SpO2",
        "systolic": "Sys",
        "diastolic": "Dia",
        "glucose": "Glu",
        "temperature": "Temp",
        "context": "Context",
        "total_measurements": "Total measurements",
        "monitoring_period": "Monitoring period",
        "to": "to",
        "medications_adherence": "Medications & Adherence",
        "medication": "Medication",
        "dose": "Dose",
        "schedule": "Schedule",
        "days": "Days",
        "active": "Active",
        "inactive": "Inactive",
        "resolved": "Resolved",
        "adherence": "Adherence",
        "yes": "Yes",
        "no": "No",
        "no_data": "No data recorded",
        "legal_notice": (
            "This document is a summary of the digital clinical record generated by the RMHealth system. "
            "The data contained herein is informational and does not replace professional medical judgment. "
            "Minimum retention of 5 years per NOM-004-SSA3-2012."
        ),
        "confidential": "CONFIDENTIAL — Protected medical information",
        "special_instructions": "Special Instructions",
    },
}

# ── Colors ───────────────────────────────────────────────────────
TEAL = colors.HexColor("#1B7A6E")
TEAL_LIGHT = colors.HexColor("#E0F2F1")
DARK = colors.HexColor("#1E293B")
GRAY_ALT = colors.HexColor("#F8FAFC")
GRAY_BORDER = colors.HexColor("#E2E8F0")
RED = colors.HexColor("#EF4444")


class ExpedientePDFGenerator:
    """Generates a complete clinical record PDF."""

    def __init__(self, language: str = "es"):
        self.lang = language if language in TRANSLATIONS else "es"
        self.t = TRANSLATIONS[self.lang]
        self.styles = getSampleStyleSheet()
        self._setup_styles()

    def _setup_styles(self):
        """Configure custom paragraph styles."""
        self.styles.add(ParagraphStyle(
            name="SectionTitle",
            fontName="Helvetica-Bold",
            fontSize=14,
            textColor=TEAL,
            spaceBefore=16,
            spaceAfter=8,
        ))
        self.styles.add(ParagraphStyle(
            name="FieldLabel",
            fontName="Helvetica-Bold",
            fontSize=9,
            textColor=DARK,
        ))
        self.styles.add(ParagraphStyle(
            name="FieldValue",
            fontName="Helvetica",
            fontSize=9,
            textColor=DARK,
        ))
        self.styles.add(ParagraphStyle(
            name="SmallGray",
            fontName="Helvetica",
            fontSize=7,
            textColor=colors.HexColor("#94A3B8"),
        ))
        self.styles.add(ParagraphStyle(
            name="LegalText",
            fontName="Helvetica",
            fontSize=7,
            textColor=colors.HexColor("#64748B"),
            leading=10,
        ))

    def generate(
        self,
        profile: Dict[str, Any],
        vitals: List[Dict[str, Any]],
        medications: List[Dict[str, Any]],
        conditions: List[Dict[str, Any]],
        allergies_list: List[Dict[str, Any]],
        contacts: List[Dict[str, Any]],
        adherence: Optional[Dict[str, Any]] = None,
    ) -> bytes:
        """Generate the complete PDF and return as bytes."""
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            topMargin=0.6 * inch,
            bottomMargin=0.8 * inch,
            leftMargin=0.6 * inch,
            rightMargin=0.6 * inch,
        )

        story = []
        now = datetime.datetime.now(datetime.timezone.utc)

        # ── PAGE 1: Profile ──────────────────────────────────────
        story.extend(self._build_header(now))
        story.extend(self._build_profile(profile))
        story.extend(self._build_conditions(conditions))
        story.extend(self._build_allergies(allergies_list))
        story.extend(self._build_contacts(contacts))

        # ── PAGE 2+: Measurement History ─────────────────────────
        story.append(PageBreak())
        story.extend(self._build_vitals(vitals))

        # ── LAST PAGE: Medications ───────────────────────────────
        story.append(PageBreak())
        story.extend(self._build_medications(medications, adherence))

        # ── Legal footer ─────────────────────────────────────────
        story.append(Spacer(1, 24))
        story.append(HRFlowable(width="100%", thickness=0.5, color=GRAY_BORDER))
        story.append(Spacer(1, 6))
        story.append(Paragraph(self.t["legal_notice"], self.styles["LegalText"]))
        story.append(Spacer(1, 4))
        story.append(Paragraph(self.t["confidential"], self.styles["LegalText"]))

        # Build with footer
        doc.build(story, onFirstPage=self._page_footer, onLaterPages=self._page_footer)
        return buffer.getvalue()

    def _page_footer(self, canvas, doc):
        """Draw footer on every page."""
        now_str = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        canvas.saveState()
        canvas.setFont("Helvetica", 7)
        canvas.setFillColor(colors.HexColor("#94A3B8"))
        canvas.drawString(
            doc.leftMargin,
            0.4 * inch,
            f"RMHealth v2.0.0 | {self.t['generated']}: {now_str}"
        )
        canvas.drawRightString(
            doc.width + doc.leftMargin,
            0.4 * inch,
            f"{self.t['page']} {doc.page}"
        )
        canvas.restoreState()

    def _build_header(self, now: datetime.datetime) -> list:
        """Build document header."""
        elements = []
        elements.append(Paragraph(self.t["title"], ParagraphStyle(
            name="DocTitle",
            fontName="Helvetica-Bold",
            fontSize=20,
            textColor=TEAL,
            spaceAfter=2,
        )))
        elements.append(Paragraph(self.t["subtitle"], self.styles["SmallGray"]))
        elements.append(Spacer(1, 4))
        elements.append(Paragraph(
            f"{self.t['generated']}: {now.strftime('%Y-%m-%d %H:%M UTC')}",
            self.styles["SmallGray"]
        ))
        elements.append(Spacer(1, 8))
        elements.append(HRFlowable(width="100%", thickness=1, color=TEAL))
        elements.append(Spacer(1, 12))
        return elements

    def _build_profile(self, profile: Dict[str, Any]) -> list:
        """Build patient profile section."""
        t = self.t
        elements = []
        elements.append(Paragraph(t["patient_profile"], self.styles["SectionTitle"]))

        fields = [
            (t["name"], profile.get("full_name", "—")),
            (t["email"], profile.get("email", "—")),
            (t["age"], f"{profile.get('age', '—')} {t['years']}" if profile.get("age") else "—"),
            (t["blood_type"], profile.get("blood_type", "—")),
            (t["weight"], f"{profile.get('weight', '—')} kg" if profile.get("weight") else "—"),
            (t["height"], f"{profile.get('height', '—')} cm" if profile.get("height") else "—"),
        ]

        if profile.get("treating_doctor_name"):
            doc_info = profile["treating_doctor_name"]
            if profile.get("treating_doctor_specialty"):
                doc_info += f" ({profile['treating_doctor_specialty']})"
            fields.append((t["treating_doctor"], doc_info))

        if profile.get("special_instructions"):
            fields.append((t["special_instructions"], profile["special_instructions"]))

        data = [[Paragraph(f"<b>{label}:</b>", self.styles["FieldLabel"]),
                 Paragraph(str(value), self.styles["FieldValue"])] for label, value in fields]

        table = Table(data, colWidths=[2.2 * inch, 4.8 * inch])
        table.setStyle(TableStyle([
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("TOPPADDING", (0, 0), (-1, -1), 3),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
            ("ROWBACKGROUNDS", (0, 0), (-1, -1), [colors.white, GRAY_ALT]),
        ]))
        elements.append(table)
        return elements

    def _build_conditions(self, conditions: List[Dict[str, Any]]) -> list:
        """Build medical conditions section."""
        t = self.t
        elements = []
        elements.append(Paragraph(t["medical_conditions"], self.styles["SectionTitle"]))

        if not conditions:
            elements.append(Paragraph(t["no_data"], self.styles["FieldValue"]))
            return elements

        header = [t["condition"], t["status"], t["diagnosis_date"]]
        data = [header]
        for c in conditions:
            diag = c.get("diagnosis_date", "—")
            if hasattr(diag, "strftime"):
                diag = diag.strftime("%Y-%m-%d")
            raw_status = c.get("status", "—")
            status_display = t.get(raw_status, raw_status)
            
            data.append([
                c.get("name", "—"),
                status_display,
                str(diag) if diag else "—",
            ])

        table = Table(data, colWidths=[3 * inch, 2 * inch, 2 * inch])
        table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), TEAL),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, GRAY_ALT]),
            ("GRID", (0, 0), (-1, -1), 0.5, GRAY_BORDER),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ]))
        elements.append(table)
        return elements

    def _build_allergies(self, allergies_list: List[Dict[str, Any]]) -> list:
        """Build allergies section."""
        t = self.t
        elements = []
        elements.append(Paragraph(t["allergies"], self.styles["SectionTitle"]))

        if not allergies_list:
            elements.append(Paragraph(t["no_data"], self.styles["FieldValue"]))
            return elements

        header = [t["agent"], t["type"], t["severity"]]
        data = [header]
        for a in allergies_list:
            data.append([
                a.get("agent", "—"),
                a.get("allergy_type", "—"),
                a.get("severity", "—"),
            ])

        table = Table(data, colWidths=[3 * inch, 2 * inch, 2 * inch])
        table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), TEAL),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, GRAY_ALT]),
            ("GRID", (0, 0), (-1, -1), 0.5, GRAY_BORDER),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ]))
        elements.append(table)
        return elements

    def _build_contacts(self, contacts: List[Dict[str, Any]]) -> list:
        """Build emergency contacts section."""
        t = self.t
        elements = []
        elements.append(Paragraph(t["emergency_contacts"], self.styles["SectionTitle"]))

        if not contacts:
            elements.append(Paragraph(t["no_data"], self.styles["FieldValue"]))
            return elements

        header = [t["contact_name"], t["relationship"], t["phone"]]
        data = [header]
        for c in contacts:
            data.append([
                c.get("name", "—"),
                c.get("relationship", "—"),
                c.get("phone", "—"),
            ])

        table = Table(data, colWidths=[3 * inch, 2 * inch, 2 * inch])
        table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), TEAL),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, GRAY_ALT]),
            ("GRID", (0, 0), (-1, -1), 0.5, GRAY_BORDER),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ]))
        elements.append(table)
        return elements

    def _build_vitals(self, vitals: List[Dict[str, Any]]) -> list:
        """Build measurement history section with table."""
        t = self.t
        elements = []
        elements.append(Paragraph(t["measurement_history"], self.styles["SectionTitle"]))

        if not vitals:
            elements.append(Paragraph(t["no_data"], self.styles["FieldValue"]))
            return elements

        # Summary
        total = len(vitals)
        first_date = vitals[-1].get("timestamp", "—") if vitals else "—"
        last_date = vitals[0].get("timestamp", "—") if vitals else "—"

        if hasattr(first_date, "strftime"):
            first_date = first_date.strftime("%Y-%m-%d")
        if hasattr(last_date, "strftime"):
            last_date = last_date.strftime("%Y-%m-%d")

        elements.append(Paragraph(
            f"{t['total_measurements']}: <b>{total}</b> | "
            f"{t['monitoring_period']}: {first_date} {t['to']} {last_date}",
            self.styles["FieldValue"]
        ))
        elements.append(Spacer(1, 8))

        # Table
        header = [t["date"], t["heart_rate"], t["spo2"], t["systolic"],
                  t["diastolic"], t["glucose"], t["temperature"]]
        data = [header]

        for v in vitals[:200]:  # Cap at 200 rows per PDF
            ts = v.get("timestamp", "—")
            if hasattr(ts, "strftime"):
                ts = ts.strftime("%Y-%m-%d %H:%M")

            data.append([
                str(ts),
                str(v.get("ritmo_cardiaco", "—")),
                str(v.get("spo2", "—")),
                str(v.get("presion_sistolica", "—")),
                str(v.get("presion_diastolica", "—")),
                str(v.get("glucosa", "—")),
                str(v.get("temperatura", "—")),
            ])

        col_widths = [1.8 * inch, 0.7 * inch, 0.7 * inch, 0.7 * inch,
                      0.7 * inch, 0.7 * inch, 0.7 * inch]
        table = Table(data, colWidths=col_widths, repeatRows=1)
        table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), TEAL),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 7),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, GRAY_ALT]),
            ("GRID", (0, 0), (-1, -1), 0.3, GRAY_BORDER),
            ("TOPPADDING", (0, 0), (-1, -1), 3),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
            ("ALIGN", (1, 0), (-1, -1), "CENTER"),
        ]))
        elements.append(table)

        if total > 200:
            elements.append(Spacer(1, 6))
            elements.append(Paragraph(
                f"... {total - 200} registros adicionales no mostrados",
                self.styles["SmallGray"]
            ))

        return elements

    def _build_medications(
        self,
        medications: List[Dict[str, Any]],
        adherence: Optional[Dict[str, Any]] = None,
    ) -> list:
        """Build medications and adherence section."""
        t = self.t
        elements = []
        elements.append(Paragraph(t["medications_adherence"], self.styles["SectionTitle"]))

        if not medications:
            elements.append(Paragraph(t["no_data"], self.styles["FieldValue"]))
            return elements

        header = [t["medication"], t["dose"], t["schedule"], t["days"], t["status"]]
        data = [header]

        for m in medications:
            days = m.get("dias_semana", [])
            if isinstance(days, list):
                days = ", ".join(days)

            horario = m.get("horario", "—")
            if hasattr(horario, "strftime"):
                horario = horario.strftime("%H:%M")

            data.append([
                m.get("nombre_medicina", "—"),
                m.get("dosis", "—"),
                str(horario),
                str(days),
                t["active"] if m.get("activo", True) else t["inactive"],
            ])

        col_widths = [2 * inch, 1.2 * inch, 1 * inch, 1.8 * inch, 1 * inch]
        table = Table(data, colWidths=col_widths, repeatRows=1)
        table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), TEAL),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, GRAY_ALT]),
            ("GRID", (0, 0), (-1, -1), 0.5, GRAY_BORDER),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ]))
        elements.append(table)

        # Adherence summary
        if adherence and adherence.get("overall_rate") is not None:
            elements.append(Spacer(1, 12))
            rate = adherence["overall_rate"]
            elements.append(Paragraph(
                f"<b>{t['adherence']}:</b> {rate:.0f}%",
                self.styles["FieldValue"]
            ))

        return elements
