-- RMHEALTH: Doctor-Patient Links Table
-- Migration for multi-actor system (MEDICO / CUIDADOR / PACIENTE)
-- PostgreSQL 15+ compatible

CREATE TABLE IF NOT EXISTS doctor_patient_links (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    doctor_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    patient_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    doctor_role TEXT NOT NULL DEFAULT 'MEDICO',  -- MEDICO or CUIDADOR
    status TEXT NOT NULL DEFAULT 'pending',       -- pending, active, revoked
    invite_code TEXT UNIQUE,                      -- 8-char code generated by doctor
    invite_expires_at TIMESTAMP WITH TIME ZONE,
    requested_by TEXT NOT NULL DEFAULT 'doctor',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    accepted_at TIMESTAMP WITH TIME ZONE,
    revoked_at TIMESTAMP WITH TIME ZONE,
    UNIQUE(doctor_id, patient_id)
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_dpl_doctor ON doctor_patient_links(doctor_id, status);
CREATE INDEX IF NOT EXISTS idx_dpl_patient ON doctor_patient_links(patient_id, status);
CREATE INDEX IF NOT EXISTS idx_dpl_invite ON doctor_patient_links(invite_code) WHERE invite_code IS NOT NULL;

-- Migration: Add columns if table already exists
ALTER TABLE doctor_patient_links ADD COLUMN IF NOT EXISTS doctor_role TEXT NOT NULL DEFAULT 'MEDICO';
ALTER TABLE doctor_patient_links ADD COLUMN IF NOT EXISTS invite_code TEXT;
ALTER TABLE doctor_patient_links ADD COLUMN IF NOT EXISTS invite_expires_at TIMESTAMP WITH TIME ZONE;

-- Add verified_professional flag to users table for doctor verification
ALTER TABLE users ADD COLUMN IF NOT EXISTS verified_professional BOOLEAN DEFAULT FALSE;
